# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

name: sixpack_release.$(rev:r)

trigger:
- main

pool:
  name: bababholenath-agentpool
  demands:
  - Agent.Name -equals DESKTOP-52JKOAC

variables:
  projectsToBuild: '**/*.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

- task: DotNetCoreCLI@2
  displayName: 'restore package'
  inputs:
    command: restore
    projects: '$(projectsToBuild)'

- task: DotNetCoreCLI@2
  displayName: 'build projects'
  inputs:
    command: build
    configuration: $(buildConfiguration)'
    projects: $(projectsToBuild)

- task: DotNetCoreCLI@2
  displayName: 'publish zip packages'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: $(projectsToBuild)
    modifyOutputPath: true
    zipAfterPublish: true

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'service-conn-bholenath'
    appType: 'webAppLinux'
    appName: 'sixpack'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
